auth_enabled: false

server:
  http_listen_port: ${LOKI_HTTP_LISTEN_PORT}
  log_level: ${LOKI_LOG_LEVEL}

common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: ${LOKI_CHUNKS_DIR}

compactor:
  working_directory: ${LOKI_COMPACTOR_DIR}

limits_config:
  retention_period: ${LOKI_RETENTION_PERIOD}
