# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import database_service_pb2 as database__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in database_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateUploadUrl = channel.unary_unary(
                '/objectstorage.ObjectStorageService/GenerateUploadUrl',
                request_serializer=database__service__pb2.GenerateUploadUrlRequest.SerializeToString,
                response_deserializer=database__service__pb2.GenerateUploadUrlResponse.FromString,
                _registered_method=True)
        self.GenerateDownloadUrl = channel.unary_unary(
                '/objectstorage.ObjectStorageService/GenerateDownloadUrl',
                request_serializer=database__service__pb2.GenerateDownloadUrlRequest.SerializeToString,
                response_deserializer=database__service__pb2.GenerateDownloadUrlResponse.FromString,
                _registered_method=True)
        self.BucketExists = channel.unary_unary(
                '/objectstorage.ObjectStorageService/BucketExists',
                request_serializer=database__service__pb2.BucketExistsRequest.SerializeToString,
                response_deserializer=database__service__pb2.BucketExistsResponse.FromString,
                _registered_method=True)
        self.CreateBucket = channel.unary_unary(
                '/objectstorage.ObjectStorageService/CreateBucket',
                request_serializer=database__service__pb2.CreateBucketRequest.SerializeToString,
                response_deserializer=database__service__pb2.CreateBucketResponse.FromString,
                _registered_method=True)
        self.RemoveBucket = channel.unary_unary(
                '/objectstorage.ObjectStorageService/RemoveBucket',
                request_serializer=database__service__pb2.RemoveBucketRequest.SerializeToString,
                response_deserializer=database__service__pb2.RemoveBucketResponse.FromString,
                _registered_method=True)
        self.RefreshAccessToken = channel.unary_unary(
                '/objectstorage.ObjectStorageService/RefreshAccessToken',
                request_serializer=database__service__pb2.RefreshAccessTokenRequest.SerializeToString,
                response_deserializer=database__service__pb2.RefreshAccessTokenResponse.FromString,
                _registered_method=True)


class ObjectStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateUploadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDownloadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshAccessToken(self, request, context):
        """Exchange a refresh token for a short-lived access token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateUploadUrl,
                    request_deserializer=database__service__pb2.GenerateUploadUrlRequest.FromString,
                    response_serializer=database__service__pb2.GenerateUploadUrlResponse.SerializeToString,
            ),
            'GenerateDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDownloadUrl,
                    request_deserializer=database__service__pb2.GenerateDownloadUrlRequest.FromString,
                    response_serializer=database__service__pb2.GenerateDownloadUrlResponse.SerializeToString,
            ),
            'BucketExists': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketExists,
                    request_deserializer=database__service__pb2.BucketExistsRequest.FromString,
                    response_serializer=database__service__pb2.BucketExistsResponse.SerializeToString,
            ),
            'CreateBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBucket,
                    request_deserializer=database__service__pb2.CreateBucketRequest.FromString,
                    response_serializer=database__service__pb2.CreateBucketResponse.SerializeToString,
            ),
            'RemoveBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBucket,
                    request_deserializer=database__service__pb2.RemoveBucketRequest.FromString,
                    response_serializer=database__service__pb2.RemoveBucketResponse.SerializeToString,
            ),
            'RefreshAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshAccessToken,
                    request_deserializer=database__service__pb2.RefreshAccessTokenRequest.FromString,
                    response_serializer=database__service__pb2.RefreshAccessTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objectstorage.ObjectStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('objectstorage.ObjectStorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectstorage.ObjectStorageService/GenerateUploadUrl',
            database__service__pb2.GenerateUploadUrlRequest.SerializeToString,
            database__service__pb2.GenerateUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectstorage.ObjectStorageService/GenerateDownloadUrl',
            database__service__pb2.GenerateDownloadUrlRequest.SerializeToString,
            database__service__pb2.GenerateDownloadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectstorage.ObjectStorageService/BucketExists',
            database__service__pb2.BucketExistsRequest.SerializeToString,
            database__service__pb2.BucketExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectstorage.ObjectStorageService/CreateBucket',
            database__service__pb2.CreateBucketRequest.SerializeToString,
            database__service__pb2.CreateBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectstorage.ObjectStorageService/RemoveBucket',
            database__service__pb2.RemoveBucketRequest.SerializeToString,
            database__service__pb2.RemoveBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectstorage.ObjectStorageService/RefreshAccessToken',
            database__service__pb2.RefreshAccessTokenRequest.SerializeToString,
            database__service__pb2.RefreshAccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
