[project]
name = "ai-forge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnxconverter-common>=1.16.0",
    "onnxruntime>=1.22.0",
    "omegaconf>=2.3.0",
    "onnx>=1.21.0",
    "onnxscript>=0.7.0",
    "opencv-python>=4.13.0.92",
    "pytest>=9.0.3",
    "pyyaml>=6.0.3",
    "requests>=2.33.1",
    "tensorboard>=2.20.0",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchinfo>=1.8.0",
    "torchvision>=0.26.0",
    "torchviz>=0.0.3",
    "tqdm>=4.67.3",
    "ultralytics>=8.4.46",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
