from dataclasses import field
from typing import Literal

from pydantic.dataclasses import dataclass


@dataclass(frozen=True)
class KafkaConsumerConfig:
    auto_offset_reset: str = "latest"
    """What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g., because that data has been deleted): 'earliest', 'latest', 'none'."""

    enable_auto_commit: bool = False
    """If True, the consumer's offset will be periodically committed in the background."""

    session_timeout_ms: int = 45000
    """The timeout used to detect consumer failures when using Kafka's group management facility."""

    max_poll_interval_ms: int = 300000
    """The maximum delay between invocations of poll() when using consumer group management. This places an upper bound on the amount of time that the consumer can be idle before fetching more records. If poll() is not called before expiration of this timeout, then the consumer is considered failed and the group will rebalance in order to reassign the partitions to another member."""


@dataclass(frozen=True)
class KafkaProducerConfig:
    acks: str = "all"
    """The number of acknowledgments the producer requires the leader to have received before considering a request complete. This controls the durability of records that are sent. Valid values are: 'all', '1', '0'."""

    enable_idempotence: bool = True
    """When set to True, the producer will ensure that exactly one copy of each message is written in the stream. If set to False, the producer may write duplicates of messages if a failure occurs during sending."""

    retries: int = 3
    """Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error."""

    linger_ms: int = 5
    """The producer groups together any records that arrive in between request transmissions into a single batched request. Normally this occurs only under load when records arrive faster than they can be sent out. However, in some circumstances, the client may want to reduce the number of requests even under moderate load. This setting accomplishes this by adding a small amount of artificial delay; that is, rather than immediately sending out a record, the producer will wait for up to the given delay to allow other records to be sent so that the sends can be batched together."""

    retry_backoff_ms: int = 1000
    """The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios."""

    compression_type: Literal["none", "gzip", "snappy", "lz4", "zstd"] = "snappy"
    """The compression type for all data generated by the producer. Valid values are: 'none ', 'gzip', 'snappy', 'lz4', 'zstd'."""


@dataclass(frozen=True)
class KafkaJobConfig:
    topic: str
    group_id: str
    event_type: str = ""
    consumer: KafkaConsumerConfig | None = None
    producer: KafkaProducerConfig | None = None

    def event_types(self) -> list[str]:
        return [et.strip() for et in self.event_type.split(",") if et.strip()]


@dataclass(frozen=True)
class KafkaConfig:
    """Configuration for Kafka messaging."""

    bootstrap_servers: str
    """A comma-separated list of host and port pairs that are the addresses of the Kafka brokers in a "bootstrap" Kafka cluster that a Kafka client connects to initially to bootstrap itself."""

    security_protocol: str
    """Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL."""

    client_id_prefix: str
    """A prefix for the client ID. This is used to identify the client in Kafka logs and metrics."""

    consumer_config: KafkaConsumerConfig
    """Configuration for Kafka consumers."""

    producer_config: KafkaProducerConfig
    """Configuration for Kafka producers."""

    jobs: dict[str, KafkaJobConfig] = field(default_factory=dict)
    """Named Kafka job bindings for runtime consumers/workers."""

# if __name__ == "__main__":
#     from src.platform.config import ConfigLoader
#     from subprocess import run

#     pwd = run(["pwd"], capture_output=True, text=True).stdout.strip()

#     config_loader = ConfigLoader.load(
#         KafkaConfig,
#         env_files=[f"{pwd}/services/model-lifecycle-service/config/.env"],
#         yaml_files=[f"{pwd}/services/model-lifecycle-service/config/model_lifecycle_orchestrator_config.yaml"],
#         section={
#             "kafka": None,
#             "kafka.defaults.consumer": "consumer_config",
#             "kafka.defaults.producer": "producer_config",
#         },
#     )
#     print(config_loader)
