from __future__ import annotations

from typing import Any, Protocol


class MlflowArtifactPort(Protocol):
    def log_artifact(self, run_id: str, local_path: str, artifact_path: str) -> None: ...

    def log_artifacts(self, run_id: str, local_dir: str, artifact_path: str) -> None: ...

    def log_text(self, run_id: str, content: str, artifact_file: str) -> None: ...

    def log_json(self, run_id: str, payload: dict[str, Any], artifact_file: str) -> None: ...

    def log_external_artifact_uri(self, run_id: str, key: str, uri: str) -> None: ...
