apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
